worker: python main.py
worker1: python main.py
worker2: python main.py
worker3: python main.py
worker4: python main.py
worker5: python main.py
worker6: python main.py
worker7: python main.py
worker8: python main.py
worker9: python main.py
worker10: python main.py
worker11: python main.py
worker12: python main.py
worker13: python main.py
worker14: python main.py
worker15: python main.py
worker16: python main.py
worker17: python main.py
worker18: python main.py
worker19: python main.py
worker20: python main.py
worker21: python main.py
worker22: python main.py
worker23: python main.py
worker24: python main.py
worker25: python main.py
worker26: python main.py
worker27: python main.py
worker28: python main.py
worker29: python main.py
worker30: python main.py
worker31: python main.py
worker32: python main.py
worker33: python main.py
worker34: python main.py
worker35: python main.py
worker36: python main.py
worker37: python main.py
worker38: python main.py
worker39: python main.py
worker40: python main.py
worker41: python main.py
worker42: python main.py
worker43: python main.py
worker44: python main.py
worker45: python main.py
worker46: python main.py
worker47: python main.py
worker48: python main.py
worker49: python main.py
worker50: python main.py
worker51: python main.py
worker52: python main.py
worker53: python main.py
worker54: python main.py
worker55: python main.py
worker56: python main.py
worker57: python main.py
worker58: python main.py
worker59: python main.py
worker60: python main.py
worker61: python main.py
worker62: python main.py
worker63: python main.py
worker64: python main.py
worker65: python main.py
worker66: python main.py
worker67: python main.py
worker68: python main.py
worker69: python main.py
worker70: python main.py
worker71: python main.py
worker72: python main.py
worker73: python main.py
worker74: python main.py
worker75: python main.py
worker76: python main.py
worker77: python main.py
worker78: python main.py
worker79: python main.py
worker80: python main.py
worker81: python main.py
worker82: python main.py
worker83: python main.py
worker84: python main.py
worker85: python main.py
worker86: python main.py
worker87: python main.py
worker88: python main.py
worker89: python main.py
worker90: python main.py
worker91: python main.py
worker92: python main.py
worker93: python main.py
worker94: python main.py
worker95: python main.py
worker96: python main.py
worker97: python main.py
worker98: python main.py
worker99: python main.py
