2086181473:AAHSLFs1Gm08t68FXdBMFFxJ0blcgN_UEJA#!/bin/bash

# Do not edit this file!

# To change authToken and owner id: 
## edit your Config Vars in heroku/app/settings and 
## restart the bot by turning the worker off and back on

echo "Creating config.json..."
cd /home/shell-bot
cat > config.json << EOF
{
    "authToken": "2086181473:AAHSLFs1Gm08t68FXdBMFFxJ0blcgN_UEJA",
    "owner": 2017343082
}
EOF
echo "Done."

echo "Starting Bot..."
node server
